# Generated by Django 5.1.2 on 2024-10-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pix',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
    ]
