# Generated by Django 5.1.2 on 2024-10-16 12:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='category')),
                ('create', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.PositiveBigIntegerField()),
                ('discount_price', models.PositiveBigIntegerField(blank=True, null=True)),
                ('main', models.ImageField(upload_to='products')),
                ('photo1', models.ImageField(upload_to='products')),
                ('photo2', models.ImageField(upload_to='products')),
                ('photo3', models.ImageField(upload_to='products')),
                ('photo4', models.ImageField(upload_to='products')),
                ('photo5', models.ImageField(upload_to='products')),
                ('delivery_date', models.CharField(max_length=50)),
                ('product_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('in_stock', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('create', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.category')),
            ],
        ),
    ]
