# Generated by Django 5.1.2 on 2024-10-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
